### PR TITLE
RareConnect connection into PhenomeCentral

### PR DESCRIPTION
**Pull request by veronikaslc**
- Removed patient name, dob from the profile page and data;
- Removed the dependency on the sha hashing library, since the name and dob aren't used anymore;
- Improve the UI of the RareConnect profile tab form;
- Changes in the profile page management: if there is any saved data prom previous connections, profile page is loaded from saved JSON.

### CODE REVIEW

**Comment by buske** [comment]
image

**Comment by buske** [comment]
There seems to be some weird UX with when the value of the token field is saved. It appears that the periodic phenotips autosave will save the token field, but it doesn't get saved when the rareconnect record is (re)loaded. As a result, if you're typing out the rareconnect token, and then load the rareconnect profile, and then navigate away, you end up with it getting saved in weird partial states.

**Comment by buske** [comment]
See above: untitled

**Comment by veronikaslc** [comment]
@buske codereview comments addressed

**Pull request merged**
